### ISSUE TITLE
I don't know how to run the game with a modified .pak file

### ISSUE THREAD

**Issue by 7darek** [Gktwo/wuwa-mod#1]
Hello, I would like to translate the game into my language, but for several days I have had problems with running the game with the modified pakchunk10-WindowsNoEditor file, which contains translation files. Can you help me run the game with translated files?

I know the translation files are located in:

Wuthering Waves Game\Client\Content\Paks\pakchunk10-WindowsNoEditor.pak"
-Client\Content\Aki\ConfigDB\en\lang_multi_text.db

but after translating the sample texts as if the game doesn't recognize them, could it be a problem with the game's patch files from Wuthering Waves Game\Client\Saved\Resources?
Could you describe to me what I should do to make the files I have translated visible in the game?
How to prepare .pak files and where to place them?
Will this work on the official server?

**Comment by Gktwo** [comment]
Run the game using the startup parameter -fileopen, you can copy the modified pak file, and rename it by adding "_p."
