### ISSUE TITLE
cmd

### ISSUE THREAD

**Issue by LONRRyy** [Gktwo/wuwa-mod#11]
The name of the file or directory name tag syntax is incorrect , when i use the cmd

**Comment by Gktwo** [comment]
Skills issue 😅

**Comment by suhelgx** [comment]
> The name of the file or directory name tag syntax is incorrect , when i use the cmd

just make a shortcut of the exe and add the command line

**Comment by LONRRyy** [comment]
> 技能问题😅

Yeah, I don't know how to program, so there will be some stupid questions

**Comment by LONRRyy** [comment]
> > 当我使用cmd时，文件或目录名称的语法不正确
> 
> 只需创建 exe 的快捷方式并添加命令行

I tried again, still the same error

**Comment by LONRRyy** [comment]
> 技能问题😅


Forgive my clumsiness, could you please spend some time making some picture tutorials?

**Comment by Gktwo** [comment]
Please use Google search

**Comment by LONRRyy** [comment]
> 请使用Google搜索


I tried it again and it worked  in game the price was changed but when I bought it it changed back to the original price

**Comment by Gktwo** [comment]
only visual,If I get free item, the police will arrest me

**Comment by LONRRyy** [comment]
> only visual,If I get free item, the police will arrest me


Yeah, could you make a menu that can switch certain functions on and off freely?
