### ISSUE TITLE
Need help for how to install  (IM NEW SORRY)

### ISSUE THREAD

**Issue by M111new** [Gktwo/wuwa-mod#14]
I had downloaded FModel and success to open the pak11 but this step cant work for me  which i could not open Client-Win64-Shipping.exe it pop out and close in the next second, im using epic game launcher, and the instruction i really cant get it i hope you can provided me a clear way to install whole thing by any language will do. Thank you so much
![image](https://github.com/Gktwo/wuwa-mod/assets/171402285/7cb1c4f5-152c-4698-8e7c-c96c10161587)

**Comment by Gktwo** [comment]
view ‘how to use’ ，not ‘how to modify’

**Comment by Gktwo** [comment]
Epic can add startup parameters to the game

**Comment by M111new** [comment]
run game with command line "-fileopenlog" (how to run this especially sorry im really newbie)

**Comment by M111new** [comment]
and for what i screenshot am i in the right track?

**Comment by SAIKO0001** [comment]
> view ‘how to use’ ，not ‘how to modify’

It's really hard to understand dude
