### ISSUE TITLE
Perception Range BUG

### ISSUE THREAD

**Issue by Gorggis86** [Gktwo/wuwa-mod#16]
Perception Range is loot range ?! if it is fix it we can interact with any npc in game or domain form far away and it will mess up the game so bad i wanted to do quest or pick a item but i have to scroll over 10 npc or items to pick/get one i need to talk/pick because Perception Range works like loot vacuum .... fix it asap or remove this option

might aswell cause bans because it vacuum everything in huge range

**Comment by M111new** [comment]
do you have problem in crashing due to shadar failure smth my laptop is 2070 super should be find in running

**Comment by Gorggis86** [comment]
> do you have problem in crashing due to shadar failure smth my laptop is 2070 super should be find in running

no i don't have any problems with game it self my probelm is vacuum range is almost huge and it vacuum everything in game included npc!!!!

**Comment by M111new** [comment]
i see i dont have the problem u got but after putting this mod i start to crashed in shadar and do you know how to open the multiplayer for dmg?

**Comment by Gktwo** [comment]
Don't consider banning when you cheat, range func is ‘work in progress’

**Comment by Gorggis86** [comment]
> Don't consider banning when you cheat, range func is ‘work in progress’

thanks for replay please fix range
