### ISSUE TITLE
what means 3.run game with command line "-fileopenlog"

### ISSUE THREAD

**Issue by littlesuho** [Gktwo/wuwa-mod#17]
i cant understand it

**Comment by jiongjiongJOJO** [comment]
> i cant understand it

Then don't understand.

**Comment by Feelzaa** [comment]
can someone tell how to use the cheat? what is the meaning of run game with command line "-fileopenlog"

**Comment by Gktwo** [comment]
startupArguments

**Comment by jiongjiongJOJO** [comment]
> can someone tell how to use the cheat? what is the meaning of run game with command line "-fileopenlog"
> 

字面意思
