### ISSUE TITLE
Question regarding logs

### ISSUE THREAD

**Issue by 44656365** [Gktwo/wuwa-mod#20]
As the [privacy policy](https://wutheringwaves.kurogames.com/p/language_en/privacy_policy.html) states, the game sends logs to the server.

"Gamelogs information, including personal account information, login logs, search and inquiry contents, item logs, milestones of the game, progress and game crash record, behavior data, moving speed, attack index, chat logs, nickname logs, and personalized signature logs" and "Game security information, including gamelogs information, hardware and operating system information, list of installed applications, running task information, progress and game crash record information"

You've stated "9.Disable log reporter", does that disable all of this? To be more clear, what is and isn't sent to the server when using this mod?

**Comment by Gktwo** [comment]
Some information cannot be blocked ，I just closed a LogReport function

**Comment by 44656365** [comment]
I found Log.D8 in Log.js. I think setting it to -1 would disable the logger altogether. I'm not too familiar with using FModel so I figured it might be something for you to look into. Thank you.

**Comment by Gktwo** [comment]
Okay, I'll take a look at this file
