### ISSUE TITLE
God Mode (no damage/infinite health) not working?

### ISSUE THREAD

**Issue by Koekieezz** [Gktwo/wuwa-mod#24]
I did install the mods correctly (make "~mods" folder in Wuthering Waves\Wuthering Waves Game\Client\Content\Paks) (if it's not installed correctly i cant spam echo and cant spam skills and spam T), everything did work wonderfully, but when i vs boss or any mobs, i get damage. Does this mean No Damage/Infinite Health not working?

![image](https://github.com/Gktwo/wuwa-mod/assets/112951868/332dd019-a2dc-4051-b706-5c8c1a889248)
![image](https://github.com/Gktwo/wuwa-mod/assets/112951868/e333637f-c263-4d43-9197-5b12975a6530)

**Comment by Jenderrr** [comment]
... you just have to put the files in "paks" not create a folder named mod

**Comment by Koekieezz** [comment]
> ... you just have to put the files in "paks" not create a folder named mod

it works anyways, the mod is loaded, also godmode got patched and working  as per now (along with x2 and x15 release)
