### ISSUE TITLE
auto pick 

### ISSUE THREAD

**Issue by craxyvirux** [Gktwo/wuwa-mod#28]
causes some quest not able to finish like "The Past is the Future: Continued - Open the object left by Shiyu"
also theres no chest when completing a puzzle.

**Comment by Gktwo** [comment]
The treasure chest has been picked up when you are not paying attention

**Comment by craxyvirux** [comment]
I have observed it doing the tetris puzzle. There were no rewards visible to me on the screen.

**Comment by SUCAMADIC** [comment]
> I have observed it doing the tetris puzzle. There were no rewards visible to me on the screen.

I experimented and open the chest with the cheat on and there's nothing but when you open the game normally the chest the you opened while using the cheat will be given to you so don't worry about it to much

**Comment by Gktwo** [comment]
Rewards won't disappear, rest assured
