### ISSUE TITLE
Getting stuck at login screen 

### ISSUE THREAD

**Issue by MappleSkZ** [Gktwo/wuwa-mod#29]
Well when I copy the new pak mod files to game folder, I'm getting stuck at login screen but when i delete them, it run normally
![image](https://github.com/Gktwo/wuwa-mod/assets/171484270/79196963-b7ec-473f-b143-b6db876a2fb2)

**Comment by xendak** [comment]
you can try deleting the folder "streamline" in Wuthering Waves\Wuthering Waves Game\Engine\Plugins\Runtime\Nvidia

**Comment by MappleSkZ** [comment]
it's still stuck
