### ISSUE TITLE
Can you add mob vacuum

### ISSUE THREAD

**Issue by George535220173** [Gktwo/wuwa-mod#38]
Yes, title said all.
+ps, add bypass for server side so it less risky for mob vacuum, auto pickup, killaura and such

**Comment by Gktwo** [comment]
add bypass for server side?Impossible guy

**Comment by George535220173** [comment]
then it's a free ban ticket for the auto pickup and such? since it spam item to their server side right?

**Comment by Gktwo** [comment]
No need to consider the server, no one can fight against it
