### ISSUE TITLE
Request [theres no issues for me]

### ISSUE THREAD

**Issue by ahaha2027** [Gktwo/wuwa-mod#4]
Can you make .pak file only include these ?
-Automatically pick up treasure/mats.
-Disable anti cheat.
-Disable log reporter.
no other things.

hope you can make it.
thanks in advice.

**Comment by Gktwo** [comment]
view readme.md and learn how to make pak

**Comment by ahaha2027** [comment]
its worked if i changed ext to txt and edit with notepad ++ ?
