### ISSUE TITLE
Is this BAN?

### ISSUE THREAD

**Issue by kazusa21** [Gktwo/wuwa-mod#43]
Is this a ban? I can't play co-op even when using the official client (without mods)
![Screenshot 2024-06-05 172811](https://github.com/Gktwo/wuwa-mod/assets/123815814/443d7687-e4d8-4c95-bd84-400b1f0a54db)

**Comment by trungdangq** [comment]
@kazusa21 go complete the Arena Champion side quest

**Comment by kazusa21** [comment]
> Don't ask anything unrelated to mods

Im sorry



> @kazusa21 go complete the Arena Champion side quest

Thanks its work, you're my savior
