### ISSUE TITLE
hit multiplier x15 bug

### ISSUE THREAD

**Issue by suhelgx** [Gktwo/wuwa-mod#9]
hit multiplier x15 make certain character skill not damage the enemy at all, maybe reduce it to x2 or x3.
Amazing mod btw!

**Comment by Gktwo** [comment]
Which roles cannot be used

**Comment by suhelgx** [comment]
> Which roles cannot be used

Calcharo, all of it "E" skill did not do any damage when using x15 mod, but all attacks seems working with x15 mod

**Comment by Gorggis86** [comment]
15x is alot and it will cause ping issue some times if yo uuse calcharo ult or jiyan too much make it around 5 so it will not cause any issue

**Comment by heksagen** [comment]
Calcharo e skill not hitting is tied to god mode, this also happens on echo skill, but I'm curious how to tweak the hit multiplier, care to show us?

**Comment by xendak** [comment]
search for OnHit, he edited that function to achieve it, you can unpak his changes and explore more on it if you'd like to understand some stuff better

**Comment by heksagen** [comment]
> search for OnHit, he edited that function to achieve it, you can unpak his changes and explore more on it if you'd like to understand some stuff better

Hi, I wanna know where do I find the god mode function?
